version: "3.9"

services:
  biocad_psql:
    image: postgres:14-alpine3.14
    container_name: "biocad_psql"
    ports:
      - "5432:5432"
    volumes:
      - ./migrations/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    environment:
      POSTGRES_PASSWORD: ${BIOCAD_DB_PASSWORD}
      POSTGRES_USER: ${BIOCAD_DB_USERNAME}
      POSTGRES_DB: ${BIOCAD_DB_NAME}
    env_file:
      - .env

  server:
    container_name: "server"
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "9000:9000"
    depends_on:
      - biocad_psql
    environment:
      POSTGRES_URL: ${BIOCAD_DB_URL}
    env_file:
      - .env